download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/madhuri75jha-my_collections1-1.0.0.tar.gz
format_version: 1.0.0
name: my_collections1
namespace: madhuri75jha
server: https://galaxy.ansible.com/api/
signatures: []
version: 1.0.0
version_url: /api/v3/plugin/ansible/content/published/collections/index/madhuri75jha/my_collections1/versions/1.0.0/
