---  

- name: Use encrypted files and templates  

  hosts: managed-node01  

  vars_files:  

    - api_variables.yml 

  

  tasks: 

    - name: Curl API URL for 200 status 

      ansible.builtin.uri: 

        url: "{{ api_url }}" 

        method: "{{ api_method }}" 
