---
- name: Handlers example
  hosts: thinknyx_servers
  become: yes

  tasks:
    - name: Install Apache web server
      ansible.builtin.apt:
        name: apache2
        state: present

    - name: Update Apache configuration
      ansible.builtin.copy:
        src: files/apache2.conf
        dest: /etc/apache2/apache2.conf
      notify: Restart Apache

  handlers:
    - name: Restart Apache
      ansible.builtin.service:
        name: apache2
        state: restarted

